[package]
name = "server"
version = "0.1.0"
authors = ["murwa <ever1337@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhai = "0.15.0"
ropey = "1.1.0"
tokio = "0.2.21"
